### ISSUE TITLE
Test does not compile in VS 2012

### ISSUE THREAD

**Issue by FrozenKiwi** [zjx20/stealer#1]
Pretty much says it all.  Trying to compile under VS 2012 gives the following errors:

warning C4003: not enough actual parameters for macro '_PP_SELECT_II_1'
...
error C3861: '_STEALER_PRINT__PP_SELECT_II_1': identifier not found

etc etc

**Comment by zjx20** [comment]
@FrozenKiwi I guest VS2012 does not support the trick at all, but I currently don't have an environment to test. Would you mind to test the method described in [this](http://bloglitb.blogspot.com/2010/07/access-to-private-members-thats-easy.html) and [that](http://bloglitb.blogspot.com/2011/12/access-to-private-members-safer.html) post on VS2012? If it works, I will try to add support for VS2012.

**Comment by FrozenKiwi** [comment]
The trick itself works (I can create the robber/stealer classes, and access private variables).

The problem actually stems from VS pre-compiler.  http://stackoverflow.com/questions/5530505/why-does-this-variadic-argument-count-macro-fail-with-vc

I tried adding the trick mentioned here, and things _almost_ work, with the one problem that we cannot count 0 arguments (and because of this, PP_IS_EMPTY always returns false.

#define TEST(...) PP_SIZE(**VAR_ARGS**)
int nArgs1 = TEST()
int nArgs2 = TEST(oneArg)
int nArgs3 = TEST(oneArg, twoArg)
compiles to 
int nArgs1 = 1
int nArgs2 = 1
int nArgs3 = 2

Based on some forum posts, I expect there is a way to get this working for VS
http://stackoverflow.com/questions/9183993/msvc-variadic-macro-expansion

I also found some incredible dense macro expansions for detecting 0 variadic args based on parenthesis or something, but...

I spent a full day digging through this stuff (mostly because it was very interesting just how much can be achieved with macro's), without successfully finding a macro to detect 0 var args.  Then I spent 10 mins implementing your template class stuff directly :).  I'm not sure if it is actually possible to workaround the issues in the VS compiler, but I would suggest just closing this issue and not supporting VS.

Pity, cause the stealer project looks pretty damn cool

**Comment by zjx20** [comment]
Thank you for responding, and I was glad to know that VS supports the trick, although there are still issues. Anyway, I will try to add support for VS before I close this issue.

**Comment by zjx20** [comment]
@FrozenKiwi Finally, I made it to work for VS2012, I spent a lot of time and plenty of code have been rewrited. Thank you for your interest in this project.

**Comment by FrozenKiwi** [comment]
Thanks zjx20 - I revisted this as I have need for this trick again!  This is very useful for testing!
