### ISSUE TITLE
Stealing const member methods does not work

### ISSUE THREAD

**Issue by neiser** [zjx20/stealer#2]
The following code does not compile (at least on GCC 6.1.1, ArchLinux):

```
struct Foo {
private:
    void callme() const {
        cout << "called" << endl;
    }
};

STEALER(stealer_Foo, Foo,
        STEAL_METHOD(void, callme)
        );  
```

I guess, one needs to have two different cases for this, and I also found a quick workaround:

Edit [line 154 of src/stealer.h](https://github.com/zjx20/stealer/blob/master/src/stealer.h#L154) and add a `const`, ie. make it read:

```
typedef ret_type(clz::*shape)(__VA_ARGS__) const; \
```

However, this breaks non-const member methods. So how to solve this correctly? Thanks for your help.

**Comment by zjx20** [comment]
Thank you for reporting this issue. I have to make some change to support this case. Fortunately, that should not be hard. I will do it when I am available, as soon as possible. So please be patient.

**Comment by zjx20** [comment]
You can now use `STEAL_CONST_METHOD()` for this case, have fun!

**Comment by neiser** [comment]
Thanks a lot. I was wondering if some "automagic" of those two cases is possible, and worked on that a bit (unsuccessfully). Anyhow, your solution is also nice!
