### ISSUE TITLE
Stealing private custom type not work

### ISSUE THREAD

**Issue by caikun-pjlab** [zjx20/stealer#3]
```
class private_t
{
private:
    int _private_int;
    std::string _private_string;
    std::map<int, char> _private_map;
    struct Storage {
        std::string haha;
        float b;
        Storage() : haha("haha"), b(10.0) {}
    };
    
    Storage _s;
};
```

I use STEAL_FIELD to steal _s, but there is a compile error
```
stealer_sample.cpp:111:31: error: 'Storage' is a private member of 'private_t'
       STEAL_FIELD(private_t::Storage, _s), // typedef helps a lot
```

how can I steal Storage _s?

**Comment by zjx20** [comment]
Thanks for trying out the project, but I'm afraid you can't do it in that way. Even if we had a way to steal the `_s` field, we wouldn't have a way to access the fields inside it (e.g. `_s.haha`) just because the `Storage` class itself is private.

**Comment by caikun-pjlab** [comment]
I see. Thank you for your reply.

**Comment by zjx20** [comment]
@caikun-pjlab It was an interesting question so I did some research. Then I realized that what I said earlier wasn't correct. If we have a way to get the `_s`, then we can actually access the fields in it. For example:

```c++
#include <iostream>

class foo {
private:
  struct bar {
    int a;
  };
  bar _bar;
public:
  foo() {
    _bar.a = 123;
  }
  bar& get_bar() { return _bar; }
};

int main() {
  foo f;

  // that's ok
  std::cout << f.get_bar().a << std::endl;

  // that's ok too
  auto bar = f.get_bar();
  std::cout << bar.a << std::endl;

  return 0;
}
```

Going back to the original question, we do have ways to steal the `_s`, for example:

```c++
#include <iostream>

class foo {
private:
  struct bar {
    int a;
  };
  bar _bar;
public:
  foo() {
    _bar.a = 123;
  }
  bar& get_bar() { return _bar; }
  void print() {
    std::cout << "from print(): " << _bar.a << std::endl;
  }
};

template<typename CLASS_TYPE, typename FIELD_TYPE, FIELD_TYPE CLASS_TYPE::* MEMBER_FIELD_PTR>
struct helper {
    friend void steal(CLASS_TYPE* target) {
        auto& s = target->*MEMBER_FIELD_PTR;
        std::cout << "from steal(): " << s.a << std::endl;
        
        // can also be modified
        s.a = 456;
        target->print();
    }
};

template struct helper<foo, decltype(foo::_bar), &foo::_bar>;

void steal(foo *target);

int main() {
  foo f;
  steal(&f);
  return 0;
}
```

The key to this is using `decltype` instead of declaring the private class type explicitly, which allows us to steal the pointer to the private member field. Even so, the stolen variable can't escape from the `steal()` function because we have no way of declaring a variable of type `bar` outside the function (since the bar class is private). So `stealer` can't support this scenario. But I hope you can get some inspiration from these code snippets.

**Comment by caikun-pjlab** [comment]
I have tried your code and it works perfectly!

Meanwhile, I don't think `decltype` is the key, because `template struct helper<foo, foo::bar, &foo::_bar>;` can also work.

Actually, the key is  the code
```
template<typename CLASS_TYPE, typename FIELD_TYPE, FIELD_TYPE CLASS_TYPE::* MEMBER_FIELD_PTR>
struct helper {};
```
which include CLASS_TYPE, FIELD_TYPE and MEMBER_FIELD_PTR, thus achieving steal without compile error.

Reasons for not reporting errors when accessing private types

> Explicit instantiation definitions ignore member access specifiers: parameter types and return types may be private.

from https://www.enseignement.polytechnique.fr/informatique/INF478/docs/Cpp/en/cpp/language/class_template.html

**Comment by zjx20** [comment]
You're right. Glad that helps.

**Comment by zjx20** [comment]
I was just inspired by an interesting technique called "loophole" (requires c++14) from [this blog](http://alexpolt.github.io/type-loophole.html), it can help the private type to escape the steal() function. The key is the `auto` keyword.

Here we go:
```c++
#include <iostream>

class foo {
private:
  struct bar {
    int a;
  };
  bar _bar;
public:
  foo() {
    _bar.a = 123;
  }
  bar& get_bar() { return _bar; }
  void print() {
    std::cout << "from print(): " << _bar.a << std::endl;
  }
};

template<typename CLASS_TYPE, typename FIELD_TYPE, FIELD_TYPE CLASS_TYPE::* MEMBER_FIELD_PTR>
struct helper {
    friend auto& steal(CLASS_TYPE* target) {
        return target->*MEMBER_FIELD_PTR;
    }
};

template struct helper<foo, foo::bar, &foo::_bar>;

auto& steal(foo *target);

int main() {
  foo f;

  auto& thebar = steal(&f);
  std::cout << "escaped! " << thebar.a << std::endl;
  thebar.a = 789;
  f.print();

  return 0;
}
```

**Comment by caikun-pjlab** [comment]
Great work! This code appears to use the `auto` keyword `return value deduction` feature, which was introduced in C++14.

https://oopscenities.net/2018/03/04/auto-return-type-deduction/
